GET http://localhost:8080/api/event HTTP/1.1

###
GET http://localhost:8080/api/event/2 HTTP/1.1

###
GET http://localhost:8080/api/resources/amenities/2 HTTP/1.1

###
POST http://localhost:8080/api/resources HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "resource": "Free Food",
    "locationId": 10
}

###
POST http://localhost:8080/api/event HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "title": "New Milwaukee Bucks Game",
    "description" : "Bucks game against Pistons",
    "date" : "2022-01-01T01:00",
    "duration" : 120,
    "capacity" : 50,
    "eventLocationId" : 1,
    "category" : "sports",
    "organizerId" : 1,
    "status" : true,
    "imageUrl" : "https://www.milwaukeedowntown.com/sites/default/files/homepage/slideshow/dtskyline3.jpg"

}
###
PUT http://localhost:8080/api/event/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

{   
    "id": 1,
    "title": "Milwaukee Bucks New Game",
    "description": "Bucks game against Pistons",
    "date": "2022-01-01T01:00:00.000+00:00",
    "duration": 60,
    "capacity": 50,
    "eventLocationId": 2,
    "category": "sports",
    "organizerId": 1,
    "status": false,
    "imageUrl": "https://www.milwaukeedowntown.com/sites/default/files/homepage/slideshow/dtskyline3.jpg",
    "attendees": 
}
###
DELETE http://localhost:8080/api/event/1 HTTP/1.1

###

GET http://localhost:8080/api/localhost:8080/api/resources HTTP/1.1

###
GET http://localhost:8080/api/event/category/new Category HTTP/1.1

###

GET http://localhost:8080/api/event/keyword/ptyfdfdf HTTP/1.1

###
GET http://localhost:8080/api/location/2 HTTP/1.1

###
GET http://localhost:8080/api/location/city/ HTTP/1.1

###
PUT http://localhost:8080/api/location/2 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "id": 2,
  "title": "High ",
  "city": "Cudahy",
  "address": "4950 S Lake Dr",
  "zipcode": 12345,
  "state": "WI"
}

###
PUT http://localhost:8080/api/location/2 HTTP/1.1
Content-Type: application/json
Accept: application/json


###

GET http://localhost:8080/user/1 HTTP/1.1


###
POST http://localhost:8080/user/create HTTP/1.1
Content-Type: application/json
Accept: application/json

{
        "fname": "John",
        "lname": "Johnson",
        "email": "jjohnson@fakeemail.com",
        "password": "password1!",
        "userName": "JohnJ",

}

###
POST http://localhost:8080/api/event/user/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "eventId" : "user",
    "User": {
        "userId" : 4,
        "fname": "Billy",
        "lname": "Johnson",
        "email": "billyjohnson@fakeemail.com",
        "password": "password1!",
        "passwordHash" : "cGFzc3dvcmQxIQo=",
        "userName": "BillyJ"
    }
    
}

###
GET http://localhost:8080/api/event/user/find/event/20 HTTP/1.1

###
POST http://localhost:8080/api/event/user/add HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "eventId": 20,
    "userId" : 7

}
###
DELETE http://localhost:8080/api/event/user/delete/user/7 HTTP/1.1